### ISSUE TITLE
[Feature Request] Select local image as wallpaper?

### ISSUE THREAD

**Issue by Darthagnon** [Jasius/EdgyTabsy#1]
Would it be possible to implement a simple selection dialog to select a local image as wallpaper?

Thank you for making this extension!

**Comment by Jasius** [comment]
Hey, that's certainly possible. Already have an idea in mind how to implement this.

**Comment by Jasius** [comment]
This is now implemented, albeit it has some limitations(super high res photos will be rejected due to size limitations and error won't be shown which isn't intuitive and might change in the future).

Changes should be live in a few days span(depends on Microsoft)
![image](https://user-images.githubusercontent.com/11031051/89132163-c9385680-d51a-11ea-9483-bed8fe847739.png)
@Darthagnon

**Comment by Darthagnon** [comment]
Thank you so much!
